### PR TITLE
Font Improvements

### LINKED ISSUE #89: Use 'Inter Display' for headings
Inter has a variant for headings/titles, that is tighter, and less tall. It would be nice to use it for headings in `Theme`.

Also, the system fallback font can be retrieved with `QFontDatabase::systemFont(QFontDatabase::TitleFont)` if system fonts are enabled.

### LINKED ISSUE #91: Add an option to use system fonts intead of built-in fonts
Member `useSystemFont` in `Theme`

### LINKED ISSUE #92: Font Issues
- Setting `fontSize` and `useSystemFont` does not change application font size and font
    - FIX NEEDED: `triggerCompleteRepaint` needs to call `QApplication::setFont()` 
- Default fonts look weird on Windows
    - FIX NEEDED: Dont do any DPI pixel to point size. `QFont::setPointSize()` handles all DPI automatically in Qt6
- Setting `useSystemFont` should follow default system sizing if `fontSize` not specified
    - FIX NEEDED: Check if `fontSize` is set in json...if it is not set and `useSystemFont` is true, use default font size, else use `fontSize` if set.

### LINKED ISSUE #94: Crash when using Qlementine through a QProxyStyle
I am trying to use the Qlementine QStyle as a Qt Creator plugin.

The Qt Creator plugin code is as simple as:

```cpp
#include <coreplugin/icontext.h>
#include <coreplugin/icore.h>
#include <coreplugin/manhattanstyle.h>

#include <extensionsystem/iplugin.h>

#include <QApplication>

#include <oclero/qlementine.hpp>

namespace Qlementine::Internal {

class QlementineStylePlugin final : public ExtensionSystem::IPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID "org.qt-project.Qt.QtCreatorPlugin" FILE "QlementineStylePlugin.json")

public:
    QlementineStylePlugin() = default;

    ~QlementineStylePlugin() final {}

    void initialize() final
    {
        auto manhattanStyle = new ManhattanStyle(QApplication::style()->name());
        manhattanStyle->setBaseStyle(new oclero::qlementine::QlementineStyle(this));

        QApplication::setStyle(manhattanStyle);
    }

    void extensionsInitialized() final {}

    ShutdownFlag aboutToShutdown() final { return SynchronousShutdown; }
};

} // namespace Qlementine::Internal

#include <qlementinestyleplugin.moc>
```

I have a Qlementine variation of https://github.com/cristianadam/qt-creator-phantomstyle and when I'm trying the plugin, it crashes with this callstack:

Image

I think it would be a great use case to get Qt Creator working reliably with Qlementine! 🤞

### PR DESCRIPTION
**Pull request by nlogozzo**
Fixes #89 
Fixes #91
Fixes #92
Fixes #94 

- [X] Adds an option to `Theme` called `useSystemFont` that can be set in the json.
- [x] Uses `QFontDatabase::TitleFont` and `Inter-Display` for title fonts
- [X] Fix font size and updating issues

### CODE REVIEW

File: lib/src/style/Theme.cpp [hunk 1]
```diff
@@ -175,8 +207,8 @@ std::optional<Theme> Theme::fromJsonDoc(const QJsonDocument& jsonDoc) {
 
 void Theme::initializeFonts() {
   // Fonts.
-  const auto defaultFont = QFont(QStringLiteral("Inter"));
-  const auto fixedFont = QFont(QStringLiteral("Roboto Mono"));
+  const auto defaultFont = useSystemFont ? QFont() : QFont(QStringLiteral("Inter"));
+  const auto fixedFont = useSystemFont ? QFont() : QFont(QStringLiteral("Roboto Mono"));
```
Comment (oclero) [inline lib/src/style/Theme.cpp:211]: You can use this instead:

- Default font : `QFontDatabase::systemFont(QFontDatabase::GeneralFont)`.
- Fixed font : `QFontDatabase::systemFont(QFontDatabase::FixedFont)`.

File: lib/include/oclero/qlementine/style/Theme.hpp [hunk 2]
```diff
@@ -199,6 +201,7 @@ class Theme {
   QPalette palette;
 
 public:
+  void setUseSystemFont(bool use);
```
Comment (oclero) [inline lib/include/oclero/qlementine/style/Theme.hpp:204]: Could you please remove this? Currently, there is no setter methods in `Theme`. The `bool` can be changed, but it's up to the caller to call `initializeFonts()` after modifying the `Theme`.

File: lib/src/style/Theme.cpp (hunk 1 above)
Comment (oclero) [reply lib/src/style/Theme.cpp:211]: Also, I've just seen that`QFontDatabase::TitleFont` exists!

Since Qlementine has fonts for headings/titles, it would be cool to add Inter-Display, Inter's tighter variant for headings.

Maybe in another PR? https://github.com/oclero/qlementine/issues/89

**Comment by oclero** [comment]
Related issue : #91

File: lib/src/style/Theme.cpp (hunk 1 above)
Comment (nlogozzo) [reply lib/src/style/Theme.cpp:211]: I could add it to this PR...shouldn't be too hard

**Comment by oclero** [comment]
Thank you! The code looks good! I'll merge it when I see how the headings look. (they should look good but I want to be sure)

**Review by oclero — APPROVED** [review]

**Comment by nlogozzo** [comment]
@oclero I found some bugs with font sizing and fonts not updating from the theme json...can I commit those fixes here?

**Comment by oclero** [comment]
You can do it in the same PR, and I'll see if everything is ok

**Comment by nlogozzo** [comment]
> You can do it in the same PR, and I'll see if everything is ok

See latest commit: https://github.com/oclero/qlementine/pull/88/commits/a253c792f94e5b05e9cd9cf407d60a6d9e301e8e

**Comment by nlogozzo** [comment]
image

Looking a lot better on here now!

**Comment by nlogozzo** [comment]
Again, just to clarify with these new changes:
- If `useSystemFont == true` and `specifiedFontSize == false` --> default system size will be used
- If `useSystemFont == true` and `specifiedFontSize == true` --> specified json font size will be used
- If `useSystemFont == false` -->default font values you provided in Theme.hpp will be used OR json values will be used if they were specified

File: lib/src/style/Theme.cpp [hunk 3]
```diff
@@ -175,44 +215,45 @@ std::optional<Theme> Theme::fromJsonDoc(const QJsonDocument& jsonDoc) {
...
-  const auto fixedFont = QFont(QStringLiteral("Roboto Mono"));
-  const auto dpi = QGuiApplication::primaryScreen()->logicalDotsPerInch();
+  const auto defaultFont = useSystemFont ? QFontDatabase::systemFont(QFontDatabase::GeneralFont) : QFont(QStringLiteral("Inter"));
+  const auto fixedFont = useSystemFont ? QFontDatabase::systemFont(QFontDatabase::FixedFont) : QFont(QStringLiteral("Roboto Mono"));
+  const auto titleFont = useSystemFont ? QFontDatabase::systemFont(QFontDatabase::TitleFont) : QFont(QStringLiteral("InterDisplay"));
+
   fontRegular = defaultFont;
   fontRegular.setWeight(QFont::Weight::Normal);
-  fontRegular.setPointSizeF(pixelSizeToPointSize(fontSize, dpi));
+  fontRegular.setPointSize(useSystemFont && !specifiedFontSize ? defaultFont.pointSize() : fontSize);
```
Comment (oclero) [inline lib/src/style/Theme.cpp:224]: Please use `setPointSizeF` instead of `setPointSize`

Comment (nlogozzo) [reply lib/src/style/Theme.cpp:224]: Why? The fontSize variables are ints not floats.

File: lib/src/style/Theme.cpp [hunk 4]
```diff
@@ -175,44 +215,45 @@ std::optional<Theme> Theme::fromJsonDoc(const QJsonDocument& jsonDoc) {
...
 
   fontCaption = defaultFont;
   fontCaption.setWeight(QFont::Weight::Normal);
-  fontCaption.setPointSizeF(pixelSizeToPointSize(fontSizeS1, dpi));
+  fontCaption.setPointSize(useSystemFont && !specifiedFontSizeS1 ? defaultFont.pointSize() : fontSizeS1);
 
   fontMonospace = fixedFont;
   fontMonospace.setWeight(QFont::Weight::Normal);
-  fontMonospace.setPointSizeF(pixelSizeToPointSize(fontSizeMonospace, dpi));
+  fontMonospace.setPointSize(useSystemFont && !specifiedFontSizeMonospace ? fixedFont.pointSize() : fontSizeMonospace);
```
Comment (oclero) [inline lib/src/style/Theme.cpp:256]: Something like this would be better (because the provided font by `QFontDatabase::systemFont()` is already at the correct system size:

```c++
fontRegular = defaultFont;
if (!useSystemFont) {
  fontRegular.setWeight(QFont::Weight::Normal);
  fontRegular.setPointSize(fontSize);
}
```

Headings need to have different sizes. You cannot use the same size for every heading level. You have to check what is the size of the font provided by `QFontDatabase::systemFont(QFontDatabase::TitleFont)`, and scale the heading font sizes according to this size. I have never tried so I don't know.

You should not add specifiedFontSize, specifiedFontSizeMonospace, specifiedFontSizeH1, specifiedFontSizeH2, etc. to the JSON theme. I want to keep it as simple as possible, and I don't want to provide lots of customization for Qlementine. Please remove that and keep only `useSystemFont`.

```c++
fontH1 = titleFont;
if (useSystemFont) {
  // Maybe scale the size provided by QFontDatabase::systemFont(QFontDatabase::TitleFont)? 
  // You have to try and see on every OS how it looks to ensure you didn't break anything.
  // ...
} else {
  fontH1.setWeight(QFont::Weight::Bold);
  fontH1.setPointSizeF(pixelSizeToPointSize(fontSizeH1, dpi));
}
```
I used `pixelSizeToPointSize` because we had issues on high-DPI displays. Before removing that, be sure that it works on all DPI (high/retina and low) on Windows, macOS and Linux, please.

Btw, `useSystemFont` could be renamed `useSystemFonts` since there a multiple system fonts, actually.

File: lib/src/style/Theme.cpp [hunk 5]
```diff
@@ -383,13 +424,16 @@ bool Theme::initializeFromJson(QJsonDocument const& jsonDoc) {
...
+    TRY_GET_BOOL_ATTRIBUTE(jsonObj, useSystemFont);
+
+    specifiedFontSize = TRY_GET_INT_ATTRIBUTE(jsonObj, fontSize);
+    specifiedFontSizeMonospace = TRY_GET_INT_ATTRIBUTE(jsonObj, fontSizeMonospace);
+    specifiedFontSizeH1 = TRY_GET_INT_ATTRIBUTE(jsonObj, fontSizeH1);
+    specifiedFontSizeH2 = TRY_GET_INT_ATTRIBUTE(jsonObj, fontSizeH2);
+    specifiedFontSizeH3 = TRY_GET_INT_ATTRIBUTE(jsonObj, fontSizeH3);
+    specifiedFontSizeH4 = TRY_GET_INT_ATTRIBUTE(jsonObj, fontSizeH4);
+    specifiedFontSizeH5 = TRY_GET_INT_ATTRIBUTE(jsonObj, fontSizeH5);
+    specifiedFontSizeS1 = TRY_GET_INT_ATTRIBUTE(jsonObj, fontSizeS1);
```
Comment (oclero) [inline lib/src/style/Theme.cpp:436]: Please remove that (see my other comment)

File: lib/src/style/Theme.cpp (hunk 3 above)
Comment (oclero) [reply lib/src/style/Theme.cpp:224]: Because someday I would like to switch to qreal values, which is the standard.

Comment (nlogozzo) [reply lib/src/style/Theme.cpp:224]: Would you like me to change the json values to be floats instead of ints?

File: lib/src/style/Theme.cpp (hunk 4 above)
Comment (nlogozzo) [reply lib/src/style/Theme.cpp]: Here is a 200% scaled application running correctly:

With `useSystemFonts`
image

Without `useSystemFonts`
image

Comment (nlogozzo) [reply lib/src/style/Theme.cpp]: > You have to check what is the size of the font provided by QFontDatabase::systemFont(QFontDatabase::TitleFont), and scale the heading font sizes according to this size. I have never tried so I don't know.

In this case we can use the heading sizes you have defined in `Theme.hpp`. Here is a group box heading with `useSystemFonts`:
image

**Comment by nlogozzo** [comment]
> Headings need to have different sizes.

@oclero I don't think this is the case. This is the case for `qlementine`, however, Qt uses the same font for all headings. 

Here's is a `GroupBox` with default QStyle:
image

Therefore, I think when `useSystemFonts` is true, we should use `TitleFont`, but not set its sizes, the same as we do for the other fonts when `useSystemFonts` is enabled.

**Comment by oclero** [comment]
> > Headings need to have different sizes.
> 
> @oclero I don't think this is the case. This is the case for `qlementine`, however, Qt uses the same font for all headings.
> 
> Here's is a `GroupBox` with default QStyle: image
> 
> Therefore, I think when `useSystemFonts` is true, we should use `TitleFont`, but not set its sizes, the same as we do for the other fonts when `useSystemFonts` is enabled.

maybe on Windows but we have to check on macOS and Linux too

**Comment by nlogozzo** [comment]
@oclero What's left to get this merged? I think we can actually leave heading sizing in for this library. Because modern UWP apps having heading features:
image

**Comment by oclero** [comment]
I've read that Qt renders ttf font better than otf fonts. I need to give it a try to check if this is true.

**Comment by oclero** [comment]
@nlogozzo wow so that's true! It's slightly better. Thanks!

**Comment by oclero** [comment]
@nlogozzo As for the headings, I want to keep the headings feature in Qlementine. Qlementine's goal is not to fit all usages, but rather have an opinionated look. So it could be nice to have size factors for headings when using system fonts, instead of using the same size everywhere.

**Comment by nlogozzo** [comment]
> So it could be nice to have size factors for headings when using system fonts, instead of using the same size everywhere.

@oclero This is how it is currently implemented in this PR. See:
image

**Comment by nlogozzo** [comment]
FYI: `qlementine` is officially in `vcpkg` now!

Could you please review this PR so I can do the same for `qlementine-icons`? https://github.com/oclero/qlementine-icons/pull/5

**Review by oclero — APPROVED** [review]
